name: WisePayNotifier
description: Monitor WisePay meal balance and send WhatsApp message when it's too low
inputs:
  wisepay_mid:
    description: "WisePay mID school identifier"
    required: true
    default: 336673
  wisepay_login:
    description: "WisePay login name (email address)"
    required: true
  wisepay_password:
    description: "WisePay password"
    required: true
  threshold:
    description: "Threshold balance below which notification is sent"
    default: 10.00
  simplepush_key:
    description: "Key for sending push notification to SimplePush app"
  twilio_account_sid:
    description: "Account SID for accessing Twilio"
  twilio_auth_token:
    description: "Auth token for accessing Twilio"
  twilio_messaging_service_sid:
    description: "Messaging Service SID for sending SMS messages from Twilio"
  twilio_sender:
    description: "Sender number or short code for sending SMS messages"
  phone_number:
    description: "Destination phone number for notification messages"
runs:
  using: docker
  image: Dockerfile
  env:
    WISEPAY_MID: ${{ inputs.wisepay_mid }}
    WISEPAY_LOGIN: ${{ inputs.wisepay_login }}
    WISEPAY_PASSWORD: ${{ inputs.wisepay_password }}
    SIMPLEPUSH_KEY: ${{ inputs.simplepush_key }}
    TWILIO_ACCOUNT_SID: ${{ inputs.twilio_account_sid }}
    TWILIO_AUTH_TOKEN: ${{ inputs.twilio_auth_token }}
    TWILIO_MESSAGING_SERVICE_SID: ${{ inputs.twilio_messaging_service_sid }}
    TWILIO_SENDER: ${{ inputs.twilio_sender }}
  args:
    - ${{ inputs.phone_number }}
    - ${{ inputs.threshold }}
