# This is a basic workflow to help you get started with Actions

name: Notifier

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 10 * * Mon-Fri'  # every weekday at 10am

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        env:
          WISEPAY_USER: ${{ secrets.WISEPAY_USER }}
          WISEPAY_PASSWORD: ${{ secrets.WISEPAY_PASSWORD }}
        run: python notifier.py
