name: Notify

on:
  schedule:
    - cron: '0 10 * * Mon-Fri'  # every weekday at 10am
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run notification script
        env:
          WISEPAY_MID: ${{ secrets.WISEPAY_MID }}
          WISEPAY_USER: ${{ secrets.WISEPAY_USER }}
          WISEPAY_PASSWORD: ${{ secrets.WISEPAY_PASSWORD }}
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
        run: python notifier.py
